# SET GPU AND DATATYPE
# VERIFY VRAM AVAILABILITY, FOLLOWING "GPU-MEMORY-UTILIZATION"
# Set up distributed settings (DP / TP / PP / EP, etc.)
# INSTANTIATES "MODEL_RUNNER_V1.PY"
# INSTANTIATES "INPUT_BATCH.PY"
